<div id="carouselExampleDark" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="resources/images/home-banner.jpg" class="d-block w-100" alt="Banner1">
      <div class="carousel-caption d-none d-md-block">
        <div class="container">
            <h2>Steigenberger Resort Ras Soma</h2>
            <a class="btn btn-outline-primary" href="">View Project</a>
        </div>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="resources/images/home-banner.jpg" class="d-block w-100" alt="Banner2">
      <div class="carousel-caption d-none d-md-block">
        <div class="container">
            <h2>Steigenberger Resort Ras Soma</h2>
            <a class="btn btn-outline-primary" href="">View Project</a>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img src="resources/images/home-banner.jpg" class="d-block w-100" alt="Banner3">
      <div class="carousel-caption d-none d-md-block">
        <div class="container">
            <h2>Steigenberger Resort Ras Soma</h2>
            <a class="btn btn-outline-primary" href="">View Project</a>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>