<footer>
  <div class="container">
   <div class="row">
    <div class="col-md-12">
      <ul>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-linkedin"></a></li>
        </ul>
    </div>
    <div class="col">
      1 of 2
    </div>
    <div class="col">
      2 of 2
    </div>
  </div>
     <div class="d-flex">
      
     </div>
  </div>
</footer>

