<footer>
  <div class="container">
    <h2>Get <strong>In Touch</strong></h2>
    <div class="row">
        <div class="col-md-4">
          <h6>Address</h6>
          <ul>
            <p><strong>Website Name</strong><br/>
            GL -1, Wafi Residence,<br/>
            Umm Hurair – 2, Dubai</p></li>
            <li><i class="fa fa-phone"></i><a href="tel:9714236 0733"> +971 4 236 0733</a></li>
            <li><i class="fa fa-envelope-o"></i><a href="mailto:info@website.com">info@website.com</a></li>
          </ul>
        </div>
        <div class="col-md-4 border-left-right">
          <h6>India</h6>
          <p><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:info@website.com">info@website.com</a></p>
        </div>
        <div class="col-md-4">
          <ul class="footer-link">
            <li><a href="#">Terms of Use</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Cookie Policy</a></li>
          </ul>
        </div>
    </div>
  </div>
  <div class="copyright">
    <div class="container text-center">
      Copyright © 2021 Website. All rights reserved. Powered by ePorium | <a href="https://www.sublimis.tech/" target="_blank">Sublimis</a>
    </div>
  </div>
</footer>

