<footer>
  <div class="container">
   <div class="row">
    <div class="col-md-12">
      <ul>
          <li class="d-inline"><a href="#" class="fa fa-instagram text-white"></a></li>
          <li class="d-inline"><a href="#" class="fa fa-facebook text-white"></a></li>
          <li class="d-inline"><a href="#" class="fa fa-linkedin text-white"></a></li>
      </ul>
    </div>
    <div class="col text-white">
      Copyright © 2009. <strong>Dora El Chiaty.</strong> All rights reserved.
      <a href="" class="ps-4"><strong>Privacy Policy</strong></a>
    </div>
   
    <div class="col text-white text-end">
      Powered by <strong>Brahmaand | <a href="https://www.sublimis.tech/" target="_blank">Sublimis</strong></a>
    </div>
  </div>
     <div class="d-flex">
      
     </div>
  </div>
</footer>

