<a href="#" class="back-to-top"><i class="fas fa-chevron-up"></i></a>

<!---- Bundle ------->
<script src="/resources/js/bootstrap.bundle.min.js"></script>
<script src="/resources/js/jquery.min.js"></script>
<script src="/resources/js/owl.carousel.min.js"></script>
<script src="/resources/js/main.js"></script>
<script>
$('.menubtn').click (function(){
  $(this).toggleClass('open');
});   
</script>
<!---- Seperate
<script src="/resources/js/popper.min.js"></script>
<script src="/resources/js/bootstrap.min.js"></script>
----->
