<!-- Header Starts -->
<header class="dark">
	<nav class="navbar navbar-expand-lg navbar-light">
		<div class="container">
			<a class="navbar-brand" href="index.shtml">
				<img src="/resources/images/dora-logo.png" alt="Logo" title="Logo">
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
				
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav">
				<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					
					<div class="menubtn btn2" data-menu="2">
						<span>MENU</span><div class="icon"></div>
					</div>
				</a>
				<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
					<li><a class="dropdown-item" href="about.shtml">About</a></li>
					<li><a class="dropdown-item" href="#">Portfolio</a></li>
					<li><a class="dropdown-item" href="#">Publications</a></li>
					<li><a class="dropdown-item" href="#">Media</a></li>
					<li><a class="dropdown-item" href="#">Contact</a></li>
				</ul>
				</li>
			</ul>
			</div>
		</div>
	</nav>
</header>
<!-- Header Ends -->
