<!-- header css and script starts -->
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="/resources/css/bootstrap.min.css">

<!-- Custom styles for this template -->
<link href="/resources/css/style.css" rel="stylesheet">
<link href="/resources/css/media.css" rel="stylesheet">
<!-- header css and script ends -->

<!-- Owl Carousel css -->
<link href="/resources/css/owl.carousel.min.css" rel="stylesheet">

<!-- Font Awsome css Starts Here -->
<link href="/resources/css/fontawesome.css" rel="stylesheet">
<link href="/resources/css/fontawesome4.css" rel="stylesheet">
<!-- Font Awsome css Ends Here -->